name: Bug Report
description: Create a report to help us improve OpenMS
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        <br>
  - type: markdown
    attributes:
      value: "## Details About Your Environment"
  - type: input
    id: os
    attributes:
      label: Operating System and Hardware
      description: What operating system are you using?  Which version?  On what hardware?
      placeholder: "Example: Windows 11 on x86"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: OpenMS Version
      description: Which version and distribution of OpenMS are you using?
      placeholder: "Example: pyOpenMS 3.4"
    validations:
      required: true
  - type: dropdown
    id: installer
    attributes:
      label: Installation Method
      description: How did you install OpenMS?
      options:
        - "Official Installer"
        - "Docker"
        - "Python: Conda"
        - "Python: Bioconda"
        - "Python: pip"
        - "Linux Package"
        - "Other"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        <br>
  - type: markdown
    attributes:
      value: "## Describe the Bug"
  - type: markdown
    attributes:
      value: |
        When describing the problem you are experiencing please provide as much information as possible, including:

        * What triggered the bug?
        * The full text of any error message.
        * Output from the tool you were using.
        * Screenshots of misbehaving GUI tools.
        * Example source code for problems with pyOpenMS.

        Thank you!
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please describe the problem you are experiencing.
    validations:
      required: true
